# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0ZWRGSQLPPorE15z6pkQT6x0f3gmG3R
"""

import pandas as pd

ventas_diarias = pd.Series([10, 15, 12, 18, 20])
print("Serie ventas_diarias:")
print(ventas_diarias)

x = 20
ventas_diarias_aumentadas = ventas_diarias + x
print("\nVentas diarias aumentadas en 20:")
print(ventas_diarias_aumentadas)

suma_ventas = ventas_diarias.sum()
promedio_ventas = ventas_diarias.mean()

print("\nSuma de ventas diarias:", suma_ventas)
print("Promedio de ventas diarias:", promedio_ventas)

ventas_mayores_al_promedio = ventas_diarias > promedio_ventas
print("\nSerie booleana (True si las ventas son mayores al promedio):")
print(ventas_mayores_al_promedio)

ventas_filtradas = ventas_diarias[ventas_mayores_al_promedio]
print("\nVentas mayores al promedio:")
print(ventas_filtradas)